### ISSUE TITLE
docs don't start from scratch

### ISSUE THREAD

**Issue by ehartford** [curtis-allan/shadcn-fasthtml-framework#19]
I try to start

the first thing the docs say is:

`Add the following import statement to the top of the file where you want to use the components:`

...?

what file do I want to use the components in?

Can you please write the getting started docs from the point of view of somebody starting from complete scratch with no existing files, or components?  Ie, walk me through from an empty file system into having a runnable hello world app

thank you

**Comment by curtis-allan** [comment]
Appreciate the feedback, will look into it! Just curious, which part of the installation guide are you having trouble with? It is written with the assumption that you know the basics of FastHTML and creating an app using the framework. 

In the meantime, check out this demo video I made that shows how to get started from a fresh python venv and empty main.py file: <a href="https://x.com/CurtisJAllan/status/1833375928225067132" target="_blank">Getting Started</a>

Once you have setup the project, you can check out the individual component documentation on using them in your app.

**Comment by ehartford** [comment]
That's precisely the assumption I'm requesting you not to make

I'm requesting a simple end to end hello world with no assumption of any prior knowledge.

**Comment by curtis-allan** [comment]
> That's precisely the assumption I'm requesting you not to make
> 
> I'm requesting a simple end to end hello world with no assumption of any prior knowledge.

I hear you. Will start working on it. FastHTML has great documentation on its usage so will link to it within the new guide. Thanks again for taking the time to give your feedback very appreciated!

**Comment by curtis-allan** [comment]
Updated the setup guide on the Readme.md, should be a more concise starting point now. 

Also added a fully-styled and working demo of using the components, built over a TODO app demo created by the founder of FastHTML, Jeremy Howard. Can see the code for it <a href="https://www.shad4fasthtml.com/getting-started/shad4fast-example" target="_blank">here</a>.
