### ISSUE TITLE
shad4fast_example.md

### ISSUE THREAD

**Issue by thinker007** [curtis-allan/shadcn-fasthtml-framework#39]
In  https://github.com/curtis-allan/shadcn-fasthtml-framework/blob/main/docs/md/shad4fast_example.md  found one bug:

DialogCloseButton not found 

you shoud change to DialogClose

via : https://github.com/boonhapus/spellbook-thoughtspot/blob/c4487349cfa38a959b675602ea9fb60bee17c9ca/src/spellbook/components/shadcn/shadcn.py#L853

**Comment by curtis-allan** [comment]
Ah thanks for that, forgot to update it when I pushed the changes - fixed now
