### ISSUE TITLE
Future component requests

### ISSUE THREAD

**Issue by bevenky** [curtis-allan/shadcn-fasthtml-framework#41]
This is great progress. Thanks for your effort.

Apart from parity with Shadcn components, would be great to add the following to the roadmap:

- Select component
- Charts
- Autoform (using zod or pydantic)
    - https://github.com/vantezzen/auto-form 
- Aggrid Tables
- Drag and drop components like React flow
- WYSIWYG Editor like Tiptap/Notion 
- Kanban View

**Comment by bevenky** [comment]
@curtis-allan I am happy to sponsor this request for components if that will help fast-track this.

**Comment by curtis-allan** [comment]
@bevenky Sorry only just saw this. Can't guarantee implementing all of the above mentioned components but can definitely give it a shot. Been held up a bit with irl situation and job hunting recently, but still working on this when I can. 

You're more than welcome to that would mean the world truly, but as far as fast tracking goes I can't guarantee if/how quickly I can work on these features. Very much appreciate your support and usage from day 1!

**Comment by bevenky** [comment]
@curtis-allan  how do i connect with you over email? We can discuss the details of next steps there.

**Comment by curtis-allan** [comment]
@bevenky I'll dm you my email on x.com.

**Comment by curtis-allan** [comment]
Alternatively email is: curtisjallan98@gmail.com
